from __future__ import annotations


CANONICAL_SKILLS = [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "Flask",
    "Django",
    "FastAPI",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MongoDB",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Natural Language Processing",
    "scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Data Analysis",
    "LLM",
    "RAG",
    "LangChain",
    "Vector Database",
    "REST API",
    "API Development",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Linux",
    "Tailwind CSS",
    "HTML",
    "CSS",
    "Excel",
    "Power BI",
]


SKILL_GROUPS = {
    "Machine Learning": {
        "machine learning",
        "ml",
        "scikit-learn",
        "sklearn",
        "regression",
        "classification",
        "knn",
        "decision tree",
        "predictive modeling",
        "model training",
    },
    "NLP": {
        "nlp",
        "natural language processing",
        "text classification",
        "named entity recognition",
        "semantic search",
        "embeddings",
        "language model",
    },
    "Database": {"database", "sql", "mysql", "postgresql", "sqlite", "mongodb", "rdbms"},
    "API Development": {"api", "rest api", "flask api", "fastapi", "backend", "endpoint"},
    "Version Control": {"git", "github", "gitlab", "version control"},
    "Frontend": {"react", "javascript", "typescript", "html", "css", "tailwind"},
    "Cloud": {"aws", "azure", "gcp", "cloud", "s3", "lambda", "ec2"},
    "Containerization": {"docker", "container", "kubernetes", "k8s"},
}


DEGREES = [
    "BCA",
    "BSc",
    "MCA",
    "MSc",
    "BTech",
    "B.E",
    "BE",
    "MTech",
    "MBA",
    "Bachelor",
    "Master",
    "PhD",
]

